//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankettService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> PersonOfInterest { get; set; }
        public Nullable<int> Iduser { get; set; }
    
        public virtual Inmates Inmates { get; set; }
        public virtual Users Users { get; set; }
    }
}
