//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankettService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int FormId { get; set; }
        public string VisitorFName { get; set; }
        public string VisitorLName { get; set; }
        public int PersonOfInterest { get; set; }
        public int Phonenumber { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public int User { get; set; }
    
        public virtual Inmates Inmates { get; set; }
        public virtual Users Users { get; set; }
    }
}
